# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# mybatis 配置
mybatis:
  type-aliases-package: com.fmall.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 80KB

# 通用mapper配置
mapper:
  mappers: com.fmall.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
